export const defaultThemeVariables = {
  color: {
    orange: '#FF8440',
    orangeDark: '#E86825',
    black: '#000',
    blackLighter: '#1C1C23',
    white: '#fff',
    grey: '#9F9C99',
    greyDark: '#7f7b77',
    greyLight: '#DDDBD9',
    greyLightSecondary: '#C4C4C4',
    greyLighter: '#BFBDBC',
    beigePale: '#F9F7F3',
    beigePaleLight: '#F3EFE8',
    beigePaleDark: '#D6D2CE',
    greyBlueLight: '#f8f9fa',
    green: '#008556',
    red: '#de1c22',
  },
  margins: {
    small: '10px',
    base: '20px',
    big: '40px',
  },
}
